version: '3.8'

services:
  app:
    build:
      context: .
      target: base
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    tty: true
    stdin_open: true
